Layout/DotPosition:
  EnforcedStyle: leading

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*.rb'
